# Generated by Django 5.0.6 on 2024-07-02 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_habitacione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('propietario', models.CharField(max_length=200)),
                ('email_propietario', models.EmailField(max_length=200)),
                ('fono_propietario', models.EmailField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.habitacione')),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
    ]
