# Generated by Django 5.0.6 on 2024-07-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fono_propietario',
            field=models.IntegerField(),
        ),
    ]
